#+HUGO_BASE_DIR: ../
#+SEQ_TODO: TODO NEXT DRAFT DONE

* Home
  :PROPERTIES:
  :EXPORT_HUGO_SECTION: home
  :EXPORT_FILE_NAME: home
  :END:
 
  Welcome to my mind and my life. This is a platform for me to put down thoughts
  and track progress. This is also a way for me to publicize what I am working
  on. Basically my life sucks. I don't spend quality time with God or Ayesha.

  This bring up a good point, if there are 24-hours in a days, meaning time is
  fixed, how do you get more done? What does the Quran and Hadith say?

  Lets start with a schedule, and then add items to process into it:

  | Time     | Activity    | Monday | Tuesday | Wednesday | Thursday | Friday | Importance            |
  |----------+-------------+--------+---------+-----------+----------+--------+-----------------------|
  | 4:30 AM  | Tahajjud    |        |         |           |          |        | Connect with God      |
  | 5:00 AM  | Quran       |        |         |           |          |        | God's Systems         |
  | 5:30 AM  | Arabic      |        |         |           |          |        | God's Language        |
  | 6:00 AM  | Exercise    |        |         |           |          |        | Physical Well Being   |
  | 7:00 AM  | Misc Items  |        |         |           |          |        | Get Ready, Eat, Drive |
  | 8:00 AM  | Knowledge   |        |         |           |          |        |                       |
  | 9:30 AM  | Work        | X      | X       |           |          |        |                       |
  | 12:00 PM | Knowledge   |        |         |           |          |        |                       |
  | 12:30 PM | Lunch       | X      |         |           |          |        |                       |
  | 1:00 PM  | Work        |        |         |           |          |        |                       |
  | 3:30 PM  | Knowledge   |        |         |           |          |        |                       |
  | 5:00 PM  | Misc Items  |        |         |           |          |        |                       |
  | 6:00 PM  | Family Time | X      |         |           |          |        |                       |
  | 8:30 PM  | Music       | X      |         |           |          |        |                       |
  | 10:00 PM | Reading     |        |         |           |          |        |                       |
  | 10:30 PM | Sleep       | X      |         |           |          |        |                       |
  
  This gives you 6 hours of sleep, which is recommended by Huzur. 

** How to get a Better Sleep?
   1. Stick to a sleep schedule.
   2. Practice a relaxing bedtime ritual
   3. Exercise Daily
   4. Bedroom temperature, light and sounds
   5. Comfortable bed
   6. Use bright lights to help circadian rhythms
   7. Wind down
   8. If you can't sleep, go to another room to do something relaxing
   
   Eight hours of sleep is worthless if you spend all of it tossing and turning,
   or you only sleep for about 3-4 hours of it. One study published in the
   Journal of Psychosomatic Research concluded that quality of sleep is more
   important than quantity of sleep when it comes to feeling rested and
   rejuvenated. Trying to fix poor sleep habits by going to bed earlier is like
   trying to lose weight by spending more time at the gym without actually
   changing the duration of your workout. Once you’ve learned to optimize your
   time, you’ll see better results. Optimizing your sleep depends heavily on
   three things: preparation (building good sleep habits), environment (tweaking
   your surroundings for optimal sleep), and timing (getting the sleep you need
   when you need it). Nothing can stand in for a good night’s sleep. Today we’re
   not going to show you how to scrape by with less sleep; instead, we’re going
   to help you reboot your sleeping habits so you get the sleep you need (and
   deserve). 

   Practice Good Sleep Hygiene: Sleep hygiene is similar to your end-of-day
   personal hygiene. Just like you wash your face and brush your teeth before
   bed, sleep hygiene is an umbrella term that covers all the things you do
   leading up to sleep that help or hinder restful sleep.

   Don’t drink anything with caffeine in it after dinner. Dependent on age,
   gender, and other physiological factors the half-life of caffeine in the body
   is roughly 5-10 hours. In other words, that cup of coffee you drank at 7PM is
   still with you at midnight. Nicotine is another common stimulant; you should
   quit or make your last cigarette of the day well before bed.

   Step away from the screens. Exposing yourself to the glow of a screen before
   bed will keep you awake. Your body is hardwired to wake up when light is
   bright and go to sleep when it gets dark. If you shine a bright light in your
   face before bed you’re telling your body it’s time to perk up and be alert.
   If you absolutely must use a computer or mobile device later in the day, at
   least turn the screen brightness way down to semi-counter the effect of the
   light.

   Purge your bedroom. No computers, no television, no balancing your checkbook
   in bed, no reading over those damn TPS reports, no anything but sleeping and
   getting it on (in whatever order works best for you). 

   Don’t torture yourself. You didn’t drink any coffee, you turned off the
   computer at 7PM, you lugged the TV down to the basement, you put in ear plugs
   and pulled the shades, but it’s 11PM and you’re still tossing and turning.
   Don’t torture yourself by laying in bed frustrated. Get out of bed and do
   something that will relax you. Don’t go watch television, play video games,
   or anything else that will stimulate your brain into thinking it is time to
   wake up. Go sit in a comfortable chair and read a book for a little while.
   Sort through magazines you’re going to toss in the recycling bin and clip out
   a few interesting articles. Do something low-stress and relatively boring for
   20-30 minutes and then go lay down again. You don’t want to get in the habit
   of thinking of bedtime as unpleasant and stressful.
   
   
** Planning Out
   When you don't plan out you hit times that are free and really busy. Should
   plan out your day.

** How about Cold Showers?



** Working Items:
   - Setup draft and done items
   - Setup tags and categories to be in sync with emacs
   - Setup git / magit for push to publish automatically
   - Enable contact information, link to LinkedIn page
   - Find spell checker and use grammarly for posts
   - Add resume / CV
   - Maybe look at tracking and scheduling on website
   - Change org styling in Emacs 

* Spirituality
  :PROPERTIES:
  :EXPORT_HUGO_SECTION: spirituality
  :EXPORT_FILE_NAME: _index
  :EXPORT_HUGO_MENU: :menu "main"
  :EXPORT_HUGO_CUSTOM_FRONT_MATTER: :toc true :type docs
  :END:
  
* Life Skills
  :PROPERTIES:
  :EXPORT_HUGO_SECTION: life_skills 
  :EXPORT_FILE_NAME: _index
  :EXPORT_HUGO_MENU: :menu "main"
  :EXPORT_HUGO_CUSTOM_FRONT_MATTER: :toc true :type docs
  :END:
  
  
* Mathematics
  :PROPERTIES:
  :EXPORT_HUGO_SECTION: mathematics
  :EXPORT_FILE_NAME: _index
  :EXPORT_HUGO_MENU: :menu "main"
  :EXPORT_HUGO_CUSTOM_FRONT_MATTER: :toc true :type docs
  :END:
  
  
* Science
  :PROPERTIES:
  :EXPORT_HUGO_SECTION: science
  :EXPORT_FILE_NAME: _index
  :EXPORT_HUGO_MENU: :menu "main"
  :EXPORT_HUGO_CUSTOM_FRONT_MATTER: :toc true :type docs
  :END:
  
  
* Machine Learning
  :PROPERTIES:
  :EXPORT_HUGO_SECTION: mlai
  :EXPORT_FILE_NAME: _index
  :EXPORT_HUGO_MENU: :menu "main"
  :EXPORT_HUGO_CUSTOM_FRONT_MATTER: :toc true :type docs
  :END:
  
  
  
* Music
  :PROPERTIES:
  :EXPORT_HUGO_SECTION: music
  :EXPORT_FILE_NAME: _index
  :EXPORT_HUGO_MENU: :menu "main"
  :EXPORT_HUGO_CUSTOM_FRONT_MATTER: :toc true :type docs
  :END:
  
* Career
  :PROPERTIES:
  :EXPORT_HUGO_SECTION: career
  :EXPORT_FILE_NAME: _index
  :EXPORT_HUGO_MENU: :menu "main"
  :EXPORT_HUGO_CUSTOM_FRONT_MATTER: :toc true :type docs
  :END:
  

** Working Items 
*** Why Smart People aren't successful
     - Old friends = Old Ideas, New people = New Ideas
     - Averse to change
     - Risk Taking, Hard work
     - Value of time
     - Abundance of options (lack of focus)
     - Future looking




  

     
