#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: life_skills 
 
* Brown - Make it Stick 
  :PROPERTIES: 
  :EXPORT_FILE_NAME: brown_make_it_stick 
  :EXPORT_HUGO_CUSTOM_FRONT_MATTER: :toc true :type docs :linktitle "Brown - Make it Stick"
  :EXPORT_HUGO_MENU: menu "life_skills"
  :END:
 
** The Brain 
   While the brain is not a muscle that gets stronger with exercise,
   the neural pathways that make up a body of learning do get
   stronger, when the memory is retrieved and the learning is
   practiced. Periodic practice arrests forgetting, strengthens
   retrieval routes, and is essential for hanging onto the knowledge
   you want to gain. Many people believe that their intellectual
   ability is hardwired from birth, and that failure to meet a
   learning challenge is an indictment of their native ability. But
   every time you learn something new, you change the brain—the
   residue of your experiences is stored. It’s true that we start
   life with the gift of our genes, but it’s also true that we become
   capable through the learning and development of mental models that
   enable us to reason, solve, and create. In other words, the
   elements that shape your intellectual abilities lie to a
   surprising extent within your own control. Understanding that this
   is so enables you to see failure as a badge of effort and a source
   of useful information—the need to dig deeper or to try a different
   strategy. The need to understand that when learning is hard,
   you’re doing important work. The evidence favoring variable
   training has been supported by recent neuroimaging studies that
   suggest that different kinds of practice engage different parts of
   the brain. The learning of motor skills from varied practice,
   which is more cognitively challenging than massed practice,
   appears to be consolidated in an area of the brain associated with
   the more difficult pro- cess of learning higher-order motor
   skills. The learning of motor skills from massed practice, on the
   other hand, appears to be consolidated in a different area of the
   brain that is used for learning more cognitively simple and less
   challenging motor skills. The inference is that learning gained
   through the less challenging, massed form of practice is encoded
   in a simpler or comparatively impoverished representation than the
   learn- ing gained from the varied and more challenging practice
   which demands more brain power and encodes the learning in a more
   flexible representation that can be applied more broadly. As Doug
   Larsen reminds us, the connections between the neurons in the
   brain are very plastic. “Making the brain work is actually what
   seems to make a difference—bringing in more complex networks, then
   using those circuits repeatedly, which makes them more robust.”
   The brain converts your perceptions into chemical and electrical
   changes that form a mental representation of the patterns you’ve
   observed. This process of converting sensory perceptions into
   meaningful representations in the brain is still not perfectly
   understood. We call the process encoding, and we call the new
   representations within the brain memory traces. Think of notes
   jotted or sketched on a scratchpad, our short-term memory.The
   process of strengthening these mental representations for
   long-term memory is called consolidation. New learning is labile:
   its meaning is not fully formed and therefore is easily
   altered. In consolidation, the brain reorganizes and stabilizes
   the memory traces. This may occur over several hours or lon- ger
   and involves deep processing of the new material, during which
   scientists believe that the brain replays or rehearses the
   learning, giving it meaning, filling in blank spots, and making
   connections to past experiences and to other knowledge al- ready
   stored in long-term memory. Prior knowledge is a pre- requisite
   for making sense of new learning, and forming those connections is
   an important task of consolidation.With continued retrieval,
   complex material can become second nature to a person and the
   mnemonic cues are no lon- ger needed: you consolidate concepts
   like Newton’s 3 laws of motion into mental models that you use as
   a kind of short- hand. Through repeated use, your brain encodes
   and “chunks” sequences of motor and cognitive actions, and your
   ability to recall and apply them becomes as automatic as habit.It
   comes down to the simple but no less profound truth that effortful
   learning changes the brain, building new connections and
   capability. This single fact—that our intellectual abilities are
   not fixed from birth but are, to a considerable degree, ours to
   shape—is a resounding answer to the nagging voice that too often
   asks us “Why bother?” We make the effort be- cause the effort
   itself extends the boundaries of our abilities. What we do shapes
   who we become and what we’re capable of doing. The more we do, the
   more we can do. To embrace this principle and reap its benefits is
   to be sustained through life by a growth mindset.And it comes down
   to the simple fact that the path to complex mastery or expert
   performance does not necessarily start from exceptional genes, but
   it most certainly entails self-discipline, grit, and persistence;
   with these qualities in healthy measure, if you want to become an
   expert, you prob- ably can.

** Calibration 
   The act of aligning your judgments of what you know and don’t know
   with objective feedback so as to avoid being carried off by the
   illusions of mastery that catch many learners by surprise at test
   time.  

   We’re all susceptible to illusions that can hijack our judg- ment
   of what we know and can do. Testing helps calibrate Learning Is
   Misunderstood ê 5 our judgments of what we’ve learned.

   One of the best habits a learner can instill in herself is regular
   self- quizzing to recalibrate her understanding of what she does
   and does not know.
   
   Most important is to make frequent use of testing and re- trieval
   practice to verify what you really do know versus what you think
   you know. Frequent low-stakes quizzes in class help the instructor
   verify that students are in fact learning as well as they appear
   to be and reveal the areas where extra atten- tion is
   needed. Doing cumulative quizzing, as Andy Sobel does in his
   political economics course, is especially powerful for
   consolidating learning and knitting the concepts from one stage of
   a course into new material encountered later. As a learner, you
   can use any number of practice techniques to self- test your
   mastery, from answering flashcards to explaining key concepts in
   your own words, and to peer instruction (see below).

   Don’t make the mistake of dropping material from your testing
   regime once you’ve gotten it correct a couple of times. If it’s
   important, it needs to be practiced, and practiced again. And
   don’t put stock in momentary gains that result from massed
   practice. Space your testing, vary your practice, keep the long
   view.

   Sometimes the most powerful feedback for calibrating your sense of
   what you do and don’t know are the mistakes you make in the field,
   assuming you survive them and are recep- tive to the lesson.

   CALIBRATION is the act of aligning your judgments of what you know
   and don’t know with objective feedback so as to avoid being
   carried off by the illusions of mastery that catch many learners
   by surprise at test time.  What is it? Everyone is subject to a
   host of cognitive illu- sions, some of which are described in
   Chapter 5. Mistaking fluency with a text for mastery of the
   underlying content is just one example. Calibration is simply the
   act of using an objective instrument to clear away illusions and
   adjust your judgment to better reflect reality. The aim is to be
   sure that your sense of what you know and can do is accurate.

** Elaboration 

   Elaboration is the process of giving new material meaning by
   expressing it in your own words and connecting it with what you
   already know. The more you can explain about the way your new
   learning relates to your prior knowledge, the stronger your grasp
   of the new learning will be, and the more connections you create
   that will help you remember it later.

   Reflection is a form of retrieval practice (What hap- pened? What
   did I do? How did it work out?), enhanced with elaboration (What
   would I do differently next time?).

   ELABORATION improves your mastery of new material and multiplies
   the mental cues available to you for later recall and application
   of it (Chapter 4).

   What is it? Elaboration is the process of finding additional
   layers of meaning in new material.

   For instance: Examples include relating the material to what you
   already know, explaining it to somebody else in your own words, or
   explaining how it relates to your life outside of class.

   A powerful form of elaboration is to discover a metaphor or visual
   image for the new material.

** Generation 
   The act of trying to answer a question or attempting to solve a
   problem rather than being presented with the information or the
   solution is known as generation.

   When you’re asked to supply an answer or a solution to something
   that’s new to you, the power of generation to aidlearning is even
   more evident. One explanation for this effect is the idea that as
   you cast about for a solution, retrieving re- lated knowledge from
   memory, you strengthen the route to a gap in your learning even
   before the answer is provided to fill it and, when you do fill it,
   connections are made to the related material that is fresh in your
   mind from the effort.

   Generation is another name for old-fashioned trial and error.

   GENERATION has the effect of making the mind more recep- tive to
   new learning.

   What is it? Generation is an attempt to answer a question or solve
   a problem before being shown the answer or the solution.

   For instance: On a small level, the act of filling in a missing
   word in a text (that is, generating the word yourself rather than
   having it supplied by the writer) results in better learning and
   memory of the text than simply reading a complete text.

** Interleaving 

** Reflection 

** Retrieval 
   The act of retrieving learning from memory has two profound
   benefits. One, it tells you what you know and don’t know, and
   therefore where to focus further study to improve the areas where
   you’re weak. Two, recalling what you have learned causes your
   brain to reconsolidate the mem- ory, which strengthens its
   connections to what you already know and makes it easier for you
   to recall in the future.To be most effective, retrieval must be
   repeated again and again, in spaced out sessions so that the
   recall, rather than becoming a mindless recitation, requires some
   cognitive ef- fort. Repeated recall appears to help memory
   consolidate into a cohesive representation in the brain and to
   strengthen and multiply the neural routes by which the knowledge
   can later be retrieved.
  
** Spaced Repetition 
   Why is spaced practice more effective than massed practice? It
   appears that embedding new learning in long-term memory requires a
   process of consolidation, in which memory traces (the brain’s
   representations of the new learning) are strength- ened, given
   meaning, and connected to prior knowledge—a process that unfolds
   over hours and may take several days. Rapid-fire practice leans on
   short-term memory. Durable learning, however, requires time for
   mental rehearsal and the other processes of consolidation.
   Variation

** Mental Structures 
   Mental models are forms of deeply entrenched and highly efficient
   skills or knowledge structures that, like habits, can be adapted
   and applied in varied circumstances. Expert performance is built
   through thousands of hours of practice in your area of expertise,
   in varying conditions, through which you accumu- late a vast
   library of such mental models that enables you to correctly
   discern a given situation and instantaneously select and execute
   the correct response.
 
* Other Things to think about
** How to schedule your time better
  This bring up a good point, if there are 24-hours in a days, meaning time is
  fixed, how do you get more done? What does the Quran and Hadith say?
  
  Lets start with a schedule, and then add items to process into it:

  | Time     | Activity    | Monday | Tuesday | Wednesday | Thursday | Friday | Importance            |
  |----------+-------------+--------+---------+-----------+----------+--------+-----------------------|
  | 4:30 AM  | Tahajjud    |        |         |           |          |        | Connect with God      |
  | 5:00 AM  | Quran       |        |         |           |          |        | God's Systems         |
  | 5:30 AM  | Arabic      |        |         |           |          |        | God's Language        |
  | 6:00 AM  | Exercise    |        |         |           |          |        | Physical Well Being   |
  | 7:00 AM  | Misc Items  |        |         |           |          |        | Get Ready, Eat, Drive |
  | 8:00 AM  | Knowledge   |        |         |           |          |        |                       |
  | 9:30 AM  | Work        | X      | X       |           |          |        |                       |
  | 12:00 PM | Knowledge   |        |         |           |          |        |                       |
  | 12:30 PM | Lunch       | X      |         |           |          |        |                       |
  | 1:00 PM  | Work        |        |         |           |          |        |                       |
  | 3:30 PM  | Knowledge   |        |         |           |          |        |                       |
  | 5:00 PM  | Misc Items  |        |         |           |          |        |                       |
  | 6:00 PM  | Family Time | X      |         |           |          |        |                       |
  | 8:30 PM  | Music       | X      |         |           |          |        |                       |
  | 10:00 PM | Reading     |        |         |           |          |        |                       |
  | 10:30 PM | Sleep       | X      |         |           |          |        |                       |
  
  This gives you 6 hours of sleep, which is recommended by Huzur. 

** How to get a Better Sleep?
   1. Stick to a sleep schedule.
   2. Practice a relaxing bedtime ritual
   3. Exercise Daily
   4. Bedroom temperature, light and sounds
   5. Comfortable bed
   6. Use bright lights to help circadian rhythms
   7. Wind down
   8. If you can't sleep, go to another room to do something relaxing
   
   Eight hours of sleep is worthless if you spend all of it tossing and turning,
   or you only sleep for about 3-4 hours of it. One study published in the
   Journal of Psychosomatic Research concluded that quality of sleep is more
   important than quantity of sleep when it comes to feeling rested and
   rejuvenated. Trying to fix poor sleep habits by going to bed earlier is like
   trying to lose weight by spending more time at the gym without actually
   changing the duration of your workout. Once you’ve learned to optimize your
   time, you’ll see better results. Optimizing your sleep depends heavily on
   three things: preparation (building good sleep habits), environment (tweaking
   your surroundings for optimal sleep), and timing (getting the sleep you need
   when you need it). Nothing can stand in for a good night’s sleep. Today we’re
   not going to show you how to scrape by with less sleep; instead, we’re going
   to help you reboot your sleeping habits so you get the sleep you need (and
   deserve). 

   Practice Good Sleep Hygiene: Sleep hygiene is similar to your end-of-day
   personal hygiene. Just like you wash your face and brush your teeth before
   bed, sleep hygiene is an umbrella term that covers all the things you do
   leading up to sleep that help or hinder restful sleep.

   Don’t drink anything with caffeine in it after dinner. Dependent on age,
   gender, and other physiological factors the half-life of caffeine in the body
   is roughly 5-10 hours. In other words, that cup of coffee you drank at 7PM is
   still with you at midnight. Nicotine is another common stimulant; you should
   quit or make your last cigarette of the day well before bed.

   Step away from the screens. Exposing yourself to the glow of a screen before
   bed will keep you awake. Your body is hardwired to wake up when light is
   bright and go to sleep when it gets dark. If you shine a bright light in your
   face before bed you’re telling your body it’s time to perk up and be alert.
   If you absolutely must use a computer or mobile device later in the day, at
   least turn the screen brightness way down to semi-counter the effect of the
   light.

   Purge your bedroom. No computers, no television, no balancing your checkbook
   in bed, no reading over those damn TPS reports, no anything but sleeping and
   getting it on (in whatever order works best for you). 

   Don’t torture yourself. You didn’t drink any coffee, you turned off the
   computer at 7PM, you lugged the TV down to the basement, you put in ear plugs
   and pulled the shades, but it’s 11PM and you’re still tossing and turning.
   Don’t torture yourself by laying in bed frustrated. Get out of bed and do
   something that will relax you. Don’t go watch television, play video games,
   or anything else that will stimulate your brain into thinking it is time to
   wake up. Go sit in a comfortable chair and read a book for a little while.
   Sort through magazines you’re going to toss in the recycling bin and clip out
   a few interesting articles. Do something low-stress and relatively boring for
   20-30 minutes and then go lay down again. You don’t want to get in the habit
   of thinking of bedtime as unpleasant and stressful.
   
** Planning Out
   When you don't plan out you hit times that are free and really busy. Should
   plan out your day.

** How about Cold Showers?
   Section not started yet


