#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: mlai

* Linear Regression 
  :PROPERTIES:
  :EXPORT_FILE_NAME: section1
  :EXPORT_HUGO_CUSTOM_FRONT_MATTER: :toc true :type docs :linktitle "Section 1"
  :EXPORT_HUGO_MENU: menu "mlai"
  :END:

** 1-Dimension 
   We'll start with a basic example of linear regression. Suppose you
   did an experiment where the car starts at a distance 0 and travels
   some known time. You want to find the speed of the car. What would
   you do? You would measure the distance travelled and divide it by
   the measured time and get an accurate speed:

   $$ v = d/t $$ 
   $$ d = vt  $$
   
   Now suppose you had some measurement errors. This could cause the
   speed to be inaccurate. By taking more measurements, you can get
   closer to the actual speed of the car.
   
   < Get plot of $y=mx$ showing some variance in measured $y$ >
   
   Linear regression is a method that can help approach a close
   approximation of the speed. Linear Regression 
   


* Section 2
  :PROPERTIES:
  :EXPORT_FILE_NAME: section2
  :EXPORT_HUGO_CUSTOM_FRONT_MATTER: :toc true :type docs :linktitle "Section 2"
  :EXPORT_HUGO_MENU: menu "mlai"
  :END:

** Subsection 2.1
   Blah blah blah
** Subsection 2.2 
   Blah blah blah two blah blah 
** Subsection 2.3
   Sup blah here


* Section 3
  :PROPERTIES:
  :EXPORT_FILE_NAME: section3
  :EXPORT_HUGO_CUSTOM_FRONT_MATTER: :toc true :type docs :linktitle "Section 3"
  :EXPORT_HUGO_MENU: menu "mlai"
  :END:

** Subsection 3.1
   Blah blah blah
** Subsection 3.2 
   Blah blah blah two blah blah 
** Subsection 3.3
   Sup blah blah here 


